spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch_example
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  quartz:
    job-store-type: jdbc

  application:
    name: spring-multi-server
